---
efi:
  mountPoint: /boot/efi
  recommendedSize: 512MiB
  minimumSize: 300MiB
  label: EFI
efiSystemPartition: /boot/efi
efiSystemPartitionSize: 512MiB
efiSystemPartitionName: EFI
defaultFileSystemType: ext4
